### ISSUE TITLE
Ultr hd movies not working

### ISSUE THREAD

**Issue by anilkuj** [eintamil/repository.eintamil#8] opened 2020-05-05 12:39 UTC
thabks for the awesome plugin! Most of the movies are working , and I have premium membership. Only one Ultra HD movie worked for me Parava malayalam  movie. When I try to play Any other ultra HD movie I get error pop us saying I need premium member ship even though I already have it and configured it . Strongly only one movie works in Ultra HD . Can u please help fix this

**Comment by eintamil** [comment] 2020-05-05 15:33
Let me understand the issue correctly. So every time you logout and login again, only one UHD movie works and rest displays error popup? Also, when you restart the device, is it same? Please let me know the below details. Device Type, Kodi Version, Eintamil App Version.

**Comment by anilkuj** [comment] 2020-05-05 16:15
No , I am basically able to play only that one movie Parava in UHD, for all
other movies it keeps saying buy premium membership even though I already
bought premium membership and have entered it in the settings.

**Comment by eintamil** [comment] 2020-05-05 16:49
Thanks for your reply. 

I guess I found the issue here.
In einthusan, Parava UHD seems to be available for all - not only for Premium members.

To check that yourself, open the below links in new incognito window in any browser.

Aadu - HD
https://einthusan.tv/movie/watch/3116/?lang=malayalam

Aadu - UHD
https://einthusan.tv/movie/watch/3116/?lang=malayalam&uhd=true

Parava - HD
https://einthusan.tv/movie/watch/2yoo/?lang=malayalam

Parava - UHD
https://einthusan.tv/movie/watch/2yoo/?lang=malayalam&uhd=true

For Aadu - UHD (or most of the UHD movies), if you are not logged in already, you will be prompted with premium membership screen.
However, for Parava - UHD, the movie starts playing and you are not prompted with premium membership screen.

Hence, I believe the issue is with your login details.

Please check if the username and password is correct in the below file:
~/.kodi/userdata/addon_data/plugin.video.einthusan2/settings.xml

Also, please ensure you are using the latest version of EinTamil addon.

**Comment by anilkuj** [comment] 2020-05-05 17:11
Awesome u were  right there was a typo , that was a weird coincidence that
Parava was the first UHD movie i tried :) and all others failed .
Thanks for your quick response !

You have made my life so easy the other Einthusan was not working well !!
DO u have plans to work on any other Indian Plugins
?

**Comment by anilkuj** [comment] 2020-05-05 17:13
Sorry one more thing not really a question , but more of a request do u
have plans to increase the movies size per page . Currently its only 6 per
page it would be good to have 25 or 50 per page would be helpful to browse
instead of the current 6 at a time

**Comment by eintamil** [comment] 2020-05-05 18:24
Nice to hear that it worked :) 

Regarding the number of items listed per page is really a limitation at einthusan end. 
It returns only 6 items per page. For example, please see the below pages:

https://einthusan.tv/movie/results/?find=Recent&lang=malayalam
https://einthusan.tv/movie/results/?find=Recent&lang=malayalam&page=2
https://einthusan.tv/movie/results/?find=Recent&lang=malayalam&page=3

Sorry for not being of much help on this :)

---

Regarding other Indian plugins: 
To be honest - I had never used any other add-ons apart from einthusan. Hence I have no clue.
If you can be more specific on the repo-name, add-on name, also share the GitHub url, I will have a look when I find time. 

I may have to close this issue - you can create new issue with the other plugin details.

**Comment by anilkuj** [comment] 2020-05-05 18:53
Thanks for checking appreciate it , one last question  :) how can i see the
movie information  ?

THanks

Anil

**Comment by eintamil** [comment] 2020-05-05 18:55
What do you mean by movie information?

**Comment by eintamil** [comment] 2020-05-05 19:00
What do you mean by movie information?
In the add-on, are you not seeing the synopsis on the left pane - below the movie thumbnail?

**Comment by anilkuj** [comment] 2020-05-05 20:29
Yes thats what i meant , i tried several different views and none of them
loads the Movie synopsis.

Thanks again for your quick response!

**Comment by eintamil** [comment] 2020-05-05 20:40
You haven't told me what version of EinTamil add-on you are using. 
And FYI - Synopsis will NOT be available for "Featured" movies list, it will be available only for Other menus like "Recently Added", etc.

**Closed** 2020-05-12 19:01 UTC

**Comment by eintamil** [comment] 2020-05-24 10:38
@anilkuj please update the latest x.0.9 version - the number of results is now 12 per page

**Comment by anilkuj** [comment] 2020-05-24 12:55
Awesome thanks for the update appreciate it!!
